337727: TopicSubscription name prefix with namespace
DEFRA/adp-aso-helm-library pull request #27
Opened 2024-03-12 15:24 UTC by ganeshg2491

# **What this PR does / why we need it**:
TopicSubscription name prefix with namespace
Relates to ADO Work Item AB#337727

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-03-12 15:28 UTC, DaRoszko requested changes
please can we link a testing run

2024-03-12 15:36 UTC, ganeshg2491 commented
> please can we link a testing run

We have PR build for this which is doing helm lint. 
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=500154&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=12f1170f-54f2-53f3-20dd-22fc7dff55f9

Or do you mean testing link for any demo service which is using this resource and test that new changes are deployed correctly?

So we have 'ffc-demo-payment-service' service which uses topicSubscription.
'https://github.com/DEFRA/ffc-demo-payment-service/blob/4508fc8faf807c0b1a7d02aa1c784eafbf2c7b8e/helm/ffc-demo-payment-service-infra/values.yaml#L12'

2024-03-12 16:24 UTC, kbabigumira submitted a review, later dismissed

2024-03-13 09:13 UTC, jeevankuduvaravindran approved these changes

2024-03-13 14:48 UTC, kbabigumira approved these changes

2024-03-13 15:21 UTC, DaRoszko approved these changes

2024-03-13 16:04 UTC, merged